architect:
- yegor256
- karato
readers:
- urn:github:1700391
- urn:github:3083819
- urn:github:3252127
- urn:github:3897832
- urn:github:526301
merge:
  commanders: []
deploy: {}
release:
  commanders:
  - yegor256