# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

appname: "Kliq"

#- use nginx to map to port 80
port: 3001

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

template: "template_toolkit"
engines:
  template_toolkit:
     encoding:  'utf8'
     start_tag: '[%'
     end_tag:   '%]'
  JSON:
    allow_blessed: '1'
    convert_blessed: '1'

session: "Kliq"
session_name: 'access_token'
session_is_http_only: 0

#logger: 'log_handler'
#log_handler:
#    file:
#      filename: debug.log
#      maxlevel: debug
#      minlevel: warning
#    screen:
#      log_to: "STDERR"
#      maxlevel: debug
#      minlevel: warning
#    dbi:
#      database   : "kliq2"
#      driver     : "mysql"
#      host       : "127.0.0.1"
#      port       : 3306
#      user       : "kliq_SSM"
#      password   : "self-expression"
#      table      : "event_log"
#      #columns    : 'level ctime cdate pid hostname caller progname mtime message'
#      #values     : '%level %time %date %pid %hostname %caller %progname %mtime %message'
#      #columns    : 'session_id user_id ip_address hostname path method level package message created'
#      #values     : '%level %time %date %pid %hostname %caller %progname %mtime %message'
#      columns : 'level hostname message'
#      values  : '%level %hostname %message'
#      maxlevel   : "error"
#      minlevel   : "emergency"
#      newline    : 0
#      message_pattern : "%L %T %D %P %H %C %S %t %m"
#      debug : 0
#      persistent: 1

asset_basepath: /var/opt/clqs-api/media

sites:
    facebook:
        name: 'Facebook'
#        client_id: '332698760077526'
#        client_secret: 'c0421bfd5fba43ac3e2e6631a92c8190'
        client_id: '1548251975469429'
        client_secret: 'f72eb73f7f75cc0d2c7c475178d51837'
        site: 'https://graph.facebook.com'
        protected_resource_path: '/me'
        #scope: 'email,read_stream,publish_stream,xmpp_login,offline_access'
        scope: 'email,user_friends'
    google:
        name: 'Google Contacts'
        client_id: '187223603206.apps.googleusercontent.com'
        client_secret: 'mIErEFb8IQx_mRyyN3A-KKM8'
        site: 'https://accounts.google.com'
        authorize_path: '/o/oauth2/auth'
        access_token_path: '/o/oauth2/token'
        scope: 'https://www.google.com/m8/feeds/ https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email'
        protected_resource_url: 'https://www.google.com/m8/feeds/contacts/default/full'
        access_token_param: 'oauth_token'
    twitter:
        name: 'Twitter'
        client_id: 'N3BxKDn3KpsOrf5asDvXug'
        client_secret: 'mAJUZoyBmQ1VCspcJwkhAMcmtfbQtTWbcBW1KiEc'
    yahoo:
        name: 'Yahoo'
        client_id: 'dj0yJmk9QWhVeDJMV0xBM3B6JmQ9WVdrOWJEUmxka1ZPTXpRbWNHbzlNVFU0TmpRNU5qSTJNZy0tJnM9Y29uc3VtZXJzZWNyZXQmeD1kZA--'
        client_secret: '45a3e64784462692763d5a42857e624cbaff2404'
        nonce: 'mAJUZoyBmQ1VCspcJwkhAMcmtfbQtTWbcBW1KiEc'
        #app_id = I4evEN34
    linkedin:
        name: 'LinkedIn'
        client_id: 'p40mcsl8uk3k'
        client_secret: 'AiyPNyVvRwndHjxA'
    rackspace:
        name: 'Rackspace CloudFiles'
        username: 'clqmobile'
        apikey: '3ffc50d840aee6ba72e0d6f4a7d4c653'
    amazon-s3:
        access_key: 'AKIAJMUVORF3C7HWB7HQ'
        secret_key: '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'
    zencoder:
        apikey: 'cb2c6adc86bb5398949a9ab2e03647ea'
    carnival:
        ios:
            bundle_id: 'com.tranzmt.tranzmtalpha'
            apikey: '58bdcb9cfb8957353fb4ea08d07a09765eab2292'    
            base_uri: 'https://api.carnivalmobile.com/v3'
        android:
            bundle_id: 'com.tranzmt.app'
            apikey: 'c51028c7733fbff64a952d361b75cbfc42dac22d'    
            base_uri: 'https://api.carnivalmobile.com/v3'

plugins:
    Email:
        #debug: 1
        ssl: 1
        driver: smtp
        host: smtp.sendgrid.net
        port: 465
        user: KLIQMOBILE
        pass: MightyITL23! 
    Redis:
        server: '127.0.0.1:6379'
        debug: 0
        encoding: utf8
        #connection_check_threshold: 30
        connections:
            test:
                server: '127.0.0.1:6380'
                debug: 1
                encoding: utf8
    DBIC:
       kliq:
           schema_class: Kliq::Schema
           #-- sqlite
           #dsn:  "dbi:SQLite:dbname=./t/var/kliq.db"
           #-- mysql
           dsn:  dbi:Pg:dbname=tranzmt_api;host=127.0.0.1
           user: tranzmt_api
           pass: express88hotels59thimble
           options:
             quote_names: 1
    "Auth::Twitter":
        consumer_key:     "N3BxKDn3KpsOrf5asDvXug"
        consumer_secret:  "mAJUZoyBmQ1VCspcJwkhAMcmtfbQtTWbcBW1KiEc"
        callback_url:     "http://api.tranzmt.it/v1/auth/twitter/callback"
        callback_success: "/auth/twitter/success"
        callback_fail:    "/auth/twitter/fail"

