---

- name: Install URL Shortener SSH Access Keys
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup( 'file',  '../../../../../pubkeys/' + item + '.pub' ) }}"
  with_items: short_ssh_users
