---

- name: Create nginx build directory and required directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/root/nginx-install/archives"
    - "/var/lib/nginx"
    - "/etc/nginx/sites-available"
    - "/etc/nginx/sites-enabled"

- name: Download nginx sources and modules
  get_url:
    url:  "{{ item.url }}"
    dest: "/root/nginx-install/archives/{{ item.dest }}"
    force: no
  with_items:
    - { url: "http://nginx.org/download/nginx-1.8.1.tar.gz", dest: "nginx-1.8.1.tar.gz" }
    - { url: "https://github.com/arut/nginx-rtmp-module/archive/v1.1.7.tar.gz", dest: "nginx-rtmp-module-1.1.7.tar.gz" }
    - { url: "https://github.com/masterzen/nginx-upload-progress-module/archive/v0.9.1.tar.gz", dest: "nginx-upload-progress-module-0.9.1.tar.gz" }

- name: Extract nginx sources and modules
  unarchive:
    src: "/root/nginx-install/archives/{{ item }}.tar.gz"
    creates: "{{ item }}"
    copy: no
    dest: "/root/nginx-install"
  with_items:
    - "nginx-1.8.1"
    - "nginx-rtmp-module-1.1.7"
    - "nginx-upload-progress-module-0.9.1"

- name: Fetch nginx modules from git
  git:
    repo: "{{ item.repo }}"
    dest: "/root/nginx-install/{{ item.dest }}"
    version: "{{ item.version }}"
    update: no
  with_items:
    - { repo: "https://github.com/vkholodkov/nginx-upload-module.git", dest: "nginx-upload-module", version: "2.2" }
    - { repo: "https://github.com/Fleshgrinder/nginx-sysvinit-script.git", dest: "nginx-sysvinit-script", version: "master" }

- name: Run nginx configure script
  shell: >
    ./configure
    --sbin-path=/usr/sbin
    --conf-path=/etc/nginx/nginx.conf
    --error-log-path=/var/log/nginx/error.log
    --pid-path=/var/run/nginx.pid
    --lock-path=/var/lock/nginx.lock
    --http-log-path=/var/log/nginx/access.log
    --http-client-body-temp-path=/var/lib/nginx/body
    --http-proxy-temp-path=/var/lib/nginx/proxy
    --http-fastcgi-temp-path=/var/lib/nginx/fastcgi
    --with-debug
    --with-http_stub_status_module
    --with-http_flv_module
    --with-http_ssl_module
    --with-http_dav_module
    --with-ipv6
    --add-module=../nginx-upload-module
    --add-module=../nginx-rtmp-module-1.1.7
    --add-module=../nginx-upload-progress-module-0.9.1
  args:
    chdir: "/root/nginx-install/nginx-1.8.1/"
    creates: "Makefile"

- name: Make and install nginx
  shell: make && make install
  args:
    chdir: "/root/nginx-install/nginx-1.8.1/"
    creates: "/usr/sbin/nginx"
