---

- name: Setup URL Shortener User Group
  group:
    name: "{{ short_user.group_name }}"
    gid:  "{{ short_user.gid }}"

- name: Setup URL Shortener User
  user:
    name: "{{ short_user.name }}"
    uid: "{{ short_user.uid }}"
    group: "{{ short_user.group_name }}"
    password: "*"
    comment: "{{ short_user.comment }}"
    shell: /bin/bash
