# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-25 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambassadors',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('firstname', models.CharField(db_column='firstName', max_length=50)),
                ('lastname', models.CharField(db_column='lastName', max_length=50)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=9)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'ambassadors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmsAsset',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('signature', models.CharField(blank=True, max_length=512, null=True)),
                ('width', models.SmallIntegerField(blank=True, null=True)),
                ('height', models.SmallIntegerField(blank=True, null=True)),
                ('is_preview', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('meta', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'cms_asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmsAssetFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=16, unique=True)),
                ('description', models.CharField(max_length=128)),
                ('mime_type', models.CharField(max_length=64)),
                ('file_extension', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('zencoder_params', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cms_asset_format',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmsMedia',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(max_length=10)),
                ('source_video', models.CharField(max_length=256)),
                ('created', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'cms_media',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('picture', models.CharField(blank=True, max_length=500, null=True)),
                ('text', models.CharField(max_length=512)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('handle', models.CharField(max_length=255)),
                ('hash', models.CharField(blank=True, max_length=35, null=True)),
                ('service', models.CharField(max_length=8)),
                ('screen_name', models.CharField(blank=True, max_length=75, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('org_name', models.CharField(blank=True, max_length=75, null=True)),
                ('org_title', models.CharField(blank=True, max_length=75, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('timezone', models.CharField(blank=True, max_length=75, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('optedin', models.IntegerField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('location', models.TextField(blank=True, null=True)),
                ('in_flight', models.IntegerField(blank=True, null=True)),
                ('vehicle_id', models.CharField(blank=True, max_length=100, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'drone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('image', models.CharField(blank=True, max_length=150, null=True)),
                ('when_occurs', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event_status', models.CharField(max_length=20)),
                ('rtmp_url', models.CharField(blank=True, max_length=150, null=True)),
                ('created', models.DateTimeField()),
                ('drone_enabled', models.IntegerField()),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kliqs',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=150, null=True)),
                ('is_emergency', models.IntegerField()),
                ('safeword', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_pin', models.IntegerField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'kliqs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('handle', models.CharField(max_length=36)),
                ('service', models.CharField(max_length=8)),
                ('ambassador_id', models.CharField(blank=True, max_length=36, null=True)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'lead',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('from_location', models.TextField(blank=True, null=True)),
                ('to_location', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OauthTokens',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('persona_id', models.CharField(blank=True, max_length=36, null=True)),
                ('token', models.CharField(max_length=4096)),
                ('secret', models.CharField(blank=True, max_length=4096, null=True)),
                ('service', models.CharField(max_length=8)),
                ('created', models.DateTimeField()),
                ('expires', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'oauth_tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_device_id', models.CharField(blank=True, max_length=36, null=True)),
                ('child_device_id', models.CharField(blank=True, max_length=36, null=True)),
                ('code', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'pair',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passphrases',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('passphrase', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'passphrases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(max_length=255)),
                ('payment_promo', models.CharField(blank=True, max_length=30, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.CharField(max_length=30)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('handle', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=8)),
                ('screen_name', models.CharField(blank=True, max_length=75, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_url', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('timezone', models.CharField(blank=True, max_length=75, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'personas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShareContactMap',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('hash', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('method', models.CharField(max_length=8)),
                ('service', models.CharField(max_length=8)),
                ('delivered', models.IntegerField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'share_contact_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('message', models.CharField(blank=True, max_length=1024, null=True)),
                ('geo_location', models.CharField(blank=True, max_length=256, null=True)),
                ('offset', models.IntegerField()),
                ('allow_reshare', models.IntegerField()),
                ('allow_location_share', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'shares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('suffix', models.CharField(max_length=6)),
                ('mime_type', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=10)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'uploads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.TextField()),
                ('email', models.CharField(max_length=128)),
                ('active', models.IntegerField()),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('profile_photo', models.TextField(blank=True, null=True)),
                ('picture', models.CharField(blank=True, max_length=500, null=True)),
                ('geo_location', models.CharField(blank=True, max_length=255, null=True)),
                ('email_verified', models.IntegerField(blank=True, null=True)),
                ('paid', models.IntegerField()),
                ('paid_before', models.DateTimeField()),
                ('swrve_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('lang', models.CharField(blank=True, max_length=255, null=True)),
                ('merged_chat_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('aireos_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('aireos_credit', models.IntegerField(blank=True, null=True)),
                ('drone_enabled', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZencoderOutputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zc_job_id', models.IntegerField()),
                ('zc_output_id', models.IntegerField()),
                ('state', models.CharField(max_length=11)),
                ('created', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'zencoder_outputs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KliqContactMap',
            fields=[
                ('kliq', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='safeword.Kliqs')),
            ],
            options={
                'db_table': 'kliq_contact_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShareKliqMap',
            fields=[
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='safeword.Shares')),
            ],
            options={
                'db_table': 'share_kliq_map',
                'managed': False,
            },
        ),
    ]
