---

- name: Install API on all API Hosts
  hosts: api_host
  remote_user: ansible
  sudo: yes

  roles:
    - maintenance/install_api_user
    - maintenance/install_api_user_ssh_keys
    - common/add_github_known_host
    - common/install_installation_packages
    - api_host/install_packages
    - api_host/install_nginx
