---

- name: Set up Development Servers with basic requirements
  hosts: dev_servers
  remote_user: ansible
  sudo: yes

  roles:
    - maintenance/setup_sshd
    - maintenance/install_users
    - common/install_installation_packages
    - api_host/install_packages
    - nginx/install_basic_dependencies
    - api_host/install_nginx
    - postgresql/setup_postgres_apt_repo
    - postgresql/install_postgres_client_9-4
    - postgresql/install_libpq-dev
