---

- name: Set up Development Servers with basic requirements
  hosts: all
  remote_user: ansible
  sudo: yes

  roles:
    - maintenance/install_users
    - common/install_installation_packages
    - api_host/install_packages
    - nginx/install_basic_dependencies
    - api_host/install_nginx
