---

- name: Pre install tasks for all nodes specified
  hosts: all # if login fails, oops
  remote_user: root
  sudo: no

  roles:
    - pre_install/install_ansible_user
    - maintenance/install_ansible_ssh_keys
