---

- name: User Access maintenance for Ansible and all other users set on the box
  hosts: all
  remote_user: ansible
  sudo: yes

  roles:
    - maintenance/install_ansible_ssh_keys
    - maintenance/install_users
