---

- name: Fetch and update master Tranzmt-Api branch
  git:
    repo: "git@github.com:TRANZMT-IT/tranzmt-api.git"
    dest: "/home/ubuntu/tranzmt-api"
    version: "master"
    update: yes
  notify:
    - reload init config
    - restart tranzmt-api
    - restart tranzmt-worker
    - restart kliqtok

# This cpanm step is not a handler, as if it dies during a setup we need to be able to re-run it.
- name: Install api and worker dependencies
  shell: source ~/perl5/perlbrew/etc/bashrc && cpanm --installdeps .
  args:
    executable: /bin/bash
    chdir: "/home/ubuntu/tranzmt-api"
  register: cpanm_tranzmt_api
  changed_when: "'installed' in cpanm_tranzmt_api.stdout"
  notify:
    - reload init config
    - restart tranzmt-api
    - restart tranzmt-worker
    - restart kliqtok

- name: Force FFmpeg::Thumbnail install
  shell: source ~/perl5/perlbrew/etc/bashrc && cpanm --notest FFmpeg::Thumbnail
  args:
    executable: /bin/bash
  register: cpanm_ffmpeg_thumbnail
  changed_when: "'is up to date' not in cpanm_ffmpeg_thumbnail.stdout"

- name: Link startup scripts
  remote_user: "{{ ansible_user.name }}"
  sudo: yes
  file:
    path: "{{ item.target }}"
    src: "{{ item.source }}"
    state: link
  with_items:
    - { source: '/home/ubuntu/tranzmt-api/etc/init/tranzmt-api.conf', target: '/etc/init/tranzmt-api.conf' }
    - { source: '/home/ubuntu/tranzmt-api/etc/init/tranzmt-worker.conf', target: '/etc/init/tranzmt-worker.conf' }
    - { source: '/home/ubuntu/tranzmt-api/kliqtok/upstart', target: '/etc/init/kliqtok.conf' }
  notify:
    - reload init config
    - restart tranzmt-api
    - restart tranzmt-worker
    - restart kliqtok
