#! /bin/sh

PLAYBOOK=$1

if [ -z $PLAYBOOK ]; then
  echo "Must provide a playbook path"
  echo "usage: $0 <playbook path>"
  exit 1
fi

NOW=$(date +"%F_%H-%M")
LOGFILE="log/$NOW.log"

echo "Writing Ansible Log to $LOGFILE"

ANSIBLE_LOG_PATH=$LOGFILE ANSIBLE_HOST_KEY_CHECKING=false ansible-playbook -i hosts $PLAYBOOK
