#! /bin/sh

NOW=$(date +"%F_%H-%M")
LOGFILE="log/$NOW.log"

echo "Writing Ansible Log to $LOGFILE"

ANSIBLE_LOG_PATH=$LOGFILE ANSIBLE_HOST_KEY_CHECKING=false ansible-playbook -i hosts playbooks/user_maintenance.yml
