---

- name: Install Nginx Basic Dependencies
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - libssl-dev
    - libpcre3
    - libpcre3-dev
